export * from './movie.interface';
export * from './genre.interface';
export * from './movies-response.interface'
export * from './companies.interface';
export * from './counties.interface';
export * from './movie-details.interface';
export * from './languages.interface';
export * from './pagination.interface';
export * from './genre-response.interface'
